[package]
name = "spectre-wallet-psst"
keywords = ["spectre", "wallet", "psst", "psbt", "bip-370"]
description = "Partially Signed Spectre Transaction"
categories = ["cryptography::cryptocurrencies"]
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
include.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
wasm32-sdk = ["spectre-consensus-client/wasm32-sdk"]
wasm32-types = ["spectre-consensus-client/wasm32-types"]

[dependencies]
spectre-addresses.workspace = true
spectre-bip32.workspace = true
spectre-consensus-client.workspace = true
spectre-consensus-core.workspace = true
spectre-txscript-errors.workspace = true
spectre-txscript.workspace = true
spectre-utils.workspace = true

bincode.workspace = true
derive_builder.workspace = true
js-sys.workspace = true
futures.workspace = true
hex.workspace = true
secp256k1.workspace = true
serde_repr.workspace = true
serde-value.workspace = true
serde.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
workflow-wasm.workspace = true

[dev-dependencies]
serde_json.workspace = true
