#!/bin/bash
# This script builds the Rusty Spectre WASM32 SDK release.

# make the script fail for any failed command
set -e

# Workaround for Rust 1.87.0
# https://github.com/rust-lang/rust/issues/141048
export RUSTFLAGS=-Ctarget-cpu=mvp

# getrandom backend for WASM32 targets (required for getrandom 0.3.*)
export RUSTFLAGS="$RUSTFLAGS --cfg getrandom_backend=\"wasm_js\""

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/spectre-wasm32-sdk/web
mkdir -p release/spectre-wasm32-sdk/nodejs
mkdir -p release/spectre-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name spectre-rpc --out-dir web/spectre-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name spectre --out-dir web/spectre-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name spectre --out-dir web/spectre-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name spectre --out-dir web/spectre-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name spectre --out-dir web/spectre-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name spectre --out-dir web/spectre-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name spectre --out-dir web/spectre-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name spectre --out-dir web/spectre --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name spectre --out-dir web/spectre-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name spectre --out-dir nodejs/spectre --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name spectre --out-dir nodejs/spectre-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name spectre --out-dir build/docs/spectre --features wasm32-sdk $@
typedoc --name "Spectre WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spectre-keygen ./build/docs/spectre-keygen.ts
typedoc --name "Spectre WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spectre-rpc ./build/docs/spectre-rpc.ts
typedoc --name "Spectre WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spectre-core ./build/docs/spectre-core.ts
typedoc --name "Spectre WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spectre ./build/docs/spectre.ts

# cp -r ../rpc/wrpc/wasm/web/spectre-rpc release/spectre-wasm32-sdk/web/spectre-rpc
cp -r web/spectre-keygen release/spectre-wasm32-sdk/web/spectre-keygen
cp -r web/spectre-keygen-dev release/spectre-wasm32-sdk/web/spectre-keygen-dev

cp -r web/spectre-rpc release/spectre-wasm32-sdk/web/spectre-rpc
cp -r web/spectre-rpc-dev release/spectre-wasm32-sdk/web/spectre-rpc-dev

cp -r web/spectre-core release/spectre-wasm32-sdk/web/spectre-core
cp -r web/spectre-core-dev release/spectre-wasm32-sdk/web/spectre-core-dev

cp -r web/spectre release/spectre-wasm32-sdk/web/spectre
cp -r web/spectre-dev release/spectre-wasm32-sdk/web/spectre-dev

cp -r nodejs/spectre release/spectre-wasm32-sdk/nodejs/spectre
cp -r nodejs/spectre-dev release/spectre-wasm32-sdk/nodejs/spectre-dev

cp -r docs/spectre-keygen release/spectre-wasm32-sdk/docs/spectre-keygen
cp -r docs/spectre-rpc release/spectre-wasm32-sdk/docs/spectre-rpc
cp -r docs/spectre-core release/spectre-wasm32-sdk/docs/spectre-core
cp -r docs/spectre release/spectre-wasm32-sdk/docs/spectre

mkdir -p release/spectre-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/spectre-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/spectre-wasm32-sdk/examples/
cp -r examples/web release/spectre-wasm32-sdk/examples/
cp -r examples/init.js release/spectre-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/spectre-wasm32-sdk/examples/
cp -r examples/package.json release/spectre-wasm32-sdk/examples/

pushd .
cd release/spectre-wasm32-sdk/examples
npm install
popd

# tsc release/spectre-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/spectre-wasm32-sdk/index.html
cp README.md release/spectre-wasm32-sdk/README.md
cp CHANGELOG.md release/spectre-wasm32-sdk/CHANGELOG.md
cp LICENSE release/spectre-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/spectre-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r spectre-wasm32-sdk.zip spectre-wasm32-sdk
popd
